### ISSUE TITLE
index.js:14 Uncaught (in promise) TypeError: api.encode is not a function

### ISSUE THREAD

**Issue by slugger941** [LinusU/node-lodepng#8]
Let me know how to solove this problem.
index.js:14 
Uncaught (in promise) TypeError: api.encode is not a function

my code is typescript and used like below.
imageData = new ImageData(width, height);
.
.
png.encode(imageData).then((res) => {
		console.log(res);
	});

**Comment by LinusU** [comment]
What is the complete stack trace? Did the installation of the package work properly? Can you try running `npm rebuild`?

It seems like there is a problem building the native part for you, could you try using [the WASM package](https://github.com/LinusU/cwasm-lodepng) and see if that works? It doesn't require any compiling at all
